# Generated by Django 4.1.1 on 2022-09-17 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars_communicator_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredcars",
            name="owner",
        ),
        migrations.AddField(
            model_name="registeredcars",
            name="owners",
            field=models.ManyToManyField(
                related_name="registeredcars_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="registeredcars",
            name="registration_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
